### PR TITLE
Upgrade Spring, Part I

### PR DESCRIPTION
**Pull request by jasonaowen**
We've been using a very old version of the Spring framework. For maintainability, security, and to enable the use of new features and libraries, we need to upgrade.

Upgrade to spring-core 4.1.9 and spring-security 3.2.10. These are not the latest versions, but the next steps are also large, and this PR is big enough on its own. More PRs are on their way!

I've been taking a stair-step approach to upgrading, as there are dependency and compatibility links between spring-core and spring-security.

To test, I've been running the Selenium tests, as well as logging in as `admin` and viewing or reviewing enrollments.

Issue #219 Upgrade Spring

### CODE REVIEW

**Comment by cecilia-donnelly** [comment]
So far I can't find any bugs in clicking around the app -- nice work, @jasonaowen!

**Comment by jasonaowen** [comment]
This is pretty big already, and the next step -- CSRF tokens -- is also pretty big. I suggest that after #501 and #500 are merged (probably in that order), I rebase and mark this as ready for review. We don't need to upgrade all the way in one PR!

**Comment by jasonaowen** [comment]
I think this is in a mergable state! Please to review.

**Comment by jasonaowen** [comment]
@cecilia-donnelly You're welcome! I'm so glad they helped. :smile:

**Pull request merged**
