### PR TITLE
Build improvements

### PR DESCRIPTION
**Pull request by jasonaowen**
Start cleaning up the build process.

This includes the excellent idea by @cecilia-donnelly of setting up a `build.properties.template` file, which is currently identical to the legacy IBM WebSphere one - I'll change it over to be more WildFly related as I change the rest of the build to be more WildFly related.

Note that as far as git is concerned, `build.xml` is pretty much entirely rewritten in 739069e, so the [whitespace-ignoring view](https://github.com/OpenTechStrategies/psm/commit/739069e6a39954fd6e779f02df4d8999ac5deb02?w=1) may be helpful in reviewing that commit. The upshot of the reformat is the next commit, ddcabd6, should be easier to read than it otherwise might be, as will future commits.

### CODE REVIEW

**Comment by slifty** [comment]
Just to make sure -- is it accurate to say that the improvements to build.xml in this PR are purely whitespace / format changes, or are there functional changes as well?

**Comment by jasonaowen** [comment]
@slifty the PR contains both formatting and functional changes, but 739069e is purely formatting. Hopefully, looking at it commit-by-commit should be clearer than looking at the "files changed" tab.

**Comment by slifty** [comment]
Thanks @jasonaowen -- I should have been more specific; 739069e is what I was asking about in particular.  (ddcabd6 is clear about what it is changing)

**Comment by jasonaowen** [comment]
@slifty ah, yes. 739069e is purely formatting, ddcabd6 is purely functional.

**Comment by slifty** [comment]
I think this is good to go!

**Pull request merged**
