### PR TITLE
Add empty checkstyle config and use with Travis

### PR DESCRIPTION
**Pull request by jasonaowen**
The first step to adopting a code style is configuring the build.

Include the checkstyle ([checkstyle project on GitHub](https://github.com/checkstyle/checkstyle), [checkstyle web page](http://checkstyle.sourceforge.net/)) [gradle plugin](https://docs.gradle.org/current/userguide/checkstyle_plugin.html), and include an empty configuration file for it to use - we'll add checks later.

Configure Travis to run the newly-defined `checkstyleMain` and `checkstyleTest` tasks as part of the build.

You may also want to install the [CheckStyle-IDEA](https://plugins.jetbrains.com/plugin/1065-checkstyle-idea) plugin, and configure it to point to `checkstyle.xml`.

---

Issue #456 Use consistent code style

### CODE REVIEW

**Comment by jasonaowen** [comment]
@cecilia-donnelly maybe make sure that you can `./gradlew checkstyle`? You're right that there shouldn't be any effect yet, since there are no rules enabled.

**Comment by cecilia-donnelly** [comment]
Good call!

```
Updating project.build.directory to psm/psm-app/integration-tests

FAILURE: Build failed with an exception.

* What went wrong:
Task 'checkstyle' is ambiguous in root project 'psm-app'. Candidates are: 'checkstyleMain', 'checkstyleTest'.

* Try:
Run gradlew tasks to get a list of available tasks. Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 0.869 secs
```

**Comment by cecilia-donnelly** [comment]
Both of the checkstyle tasks (Main and Test) pass for me!

**Comment by jasonaowen** [comment]
@cecilia-donnelly er, derp, I tested that locally, saw that same error, and then completely failed to fix it before I posted. >_< Glad the right commands worked!

**Pull request merged**
