### PR TITLE
Add logo to HTML version of user docs

### PR DESCRIPTION
**Pull request by brainwane**

### CODE REVIEW

**Comment by brainwane** [comment]
Partially towards #439.

**Comment by cecilia-donnelly** [comment]
Cool!  Can you add some padding between the logo and the "Provider Screening Module" title just below it?  The logo is also wider than the text below, which makes it look a little strange -- it sticks out to the right into a column that is mostly white space.  Nitpicks, certainly, but that's what sticks out to me.  How will this interact with #441?

**Comment by brainwane** [comment]
@cecilia-donnelly Now that I've merged #441 I think the logo padding/sizing issues you saw have melted away. Take a look?

**Comment by cecilia-donnelly** [comment]
Oh, yes, much better!

**Pull request merged**
