### PR TITLE
Improve wording in template comments and user messages

### PR DESCRIPTION
**Pull request by brainwane**
As I was getting more familiar with our templates (towards #265), I found a few user messages and comments that could use clarification. Here are a few small fixes.

### CODE REVIEW

**Comment by brainwane** [comment]
Argh, I need to fix the plurality of the user deletion modal message. When I get back from a walk!

**Comment by brainwane** [comment]
Fixed.

**Comment by jasonaowen** [comment]
@brainwane can has screenshot(s)?

**Comment by brainwane** [comment]
Single user:
delete-single-user
Multiple users (note the change in wording):
delete-multiple-accounts

**Pull request merged**
