### PR TITLE
Use 'username' consistently in user messaging

### PR DESCRIPTION
**Pull request by brainwane**
We had "username" in some places and "user name" in others. This commit fixes that inconsistency.

@jasonaowen do you want me to wrap the lines in these files as long as I am touching them?

### CODE REVIEW

**Comment by brainwane** [comment]
(For the curious: "username" is preferred in [Google's style guide](https://developers.google.com/style/word-list) and used in [the US Web Design Standards](https://standards.usa.gov/components/form-templates/#sign-in-form).)

**Comment by brainwane** [comment]
@jasonaowen Thanks. Fixed. Re-review?

**Comment by cecilia-donnelly** [comment]
Looks good!  I grepped and it looks like there are still some places in the codebase (comments mostly, but also some places in the user docs) that use "user name."  Do you want to change those in this PR?  (I don't think it needs to be a blocker, just making trouble.)

**Comment by brainwane** [comment]
@cecilia-donnelly @jasonaowen Fixed those other spots, ran tests, and all seems well. Please re-review?

**Pull request merged**
