### PR TITLE
PDF and ePub styling

### PR DESCRIPTION
**Pull request by brainwane**
Improving the styling of the PDF, and making it possible for us to generate good ePubs as well.

### CODE REVIEW

**Comment by brainwane** [comment]
I welcome thoughts from other folks on what they'd like in the styling of the PDF.

**Comment by brainwane** [comment]
@jvasile Check out [these Sphinx options for LaTeX generation](http://www.sphinx-doc.org/en/stable/config.html#options-for-latex-output) to see what's easy for me to adjust by fiddling with `conf.py`. In this change, for instance, I've added the PSM logo, page references after internal references, and footnotes with URLs. I've also changed the styling of chapter headings.

**Comment by cecilia-donnelly** [comment]
@brainwane, how should I generate the PDF to look at the cover?

**Comment by brainwane** [comment]
@cecilia-donnelly I just merged #442 recently to add those instructions in `docs/userhelp/README.mdwn`! :)

**Comment by cecilia-donnelly** [comment]
Hey, nice!  I like the logo.  :)

**Comment by cecilia-donnelly** [comment]
About #442, do I need to run the `sphinx-build` command each time the PDF changes, or will `make latexpdf` do it?

**Comment by brainwane** [comment]
@cecilia-donnelly Each time the underlying content changes, or the styling choices (as defined in `conf.py`) change, you'll have to `sphinx-build` to build the LaTeX files and then `make latexpdf` to turn those LaTeX files into a PDF. I'll add that to the documentation.

**Comment by brainwane** [comment]
Please also test whether `sphinx-build -b epub -a source/ build/epub/` works for you to build an ePub -- if so then I'll add it to the `README`.

**Comment by cecilia-donnelly** [comment]
The command you give to build an epub appears to have worked (`build succeeded, 10 warnings`), but I don't generally view epubs, so haven't tested it thoroughly.

**Comment by brainwane** [comment]
@cecilia-donnelly:

* I've fixed the page 11 problem by shortening the question that serves as the section title.
* Changing the footer is fiddly enough that I've filed it as #459.
* I've changed the titles for the chapters you mention.
* Yes, removed Chapter 8 (Indices and Tables) in #450.

I think this is ready to merge.

**Pull request merged**
