### PR TITLE
Convert flash.jsp template to handlebars

### PR DESCRIPTION
**Pull request by PaulMorris**
This 'flash' template is used to present messages like "Incorrect password." in the UI.  Here are some ways to trigger these flash messages, to test the conversion to handlebars.  For some reason you may have to click the buttons more than once to trigger the flash message.

login page > forgot password? > enter non-existant user and pwd > click reset password
"We could not retrieve your account."

Log in as a provider (p1) for the following:

profile > edit profile
"Please select the profile to be updated."

profile > renew enrollment
"Please select the profile to be renewed."

profile > change password > enter wrong current password and legit new password > click update
"Incorrect password."

Issue #238 Templatize UI

### CODE REVIEW

**Comment by cecilia-donnelly** [comment]
@PaulMorris is going to update this after we merge #500.  Holding off on review until then.

**Comment by jasonaowen** [comment]
@PaulMorris: I think mostly the changes should be removing the `<c:set>` tags and renaming the variables in the handlebars template to use the existing variables.

**Comment by PaulMorris** [comment]
Redone to reflect changes in #500. Works like a charm.  (Thank you @jasonaowen !)

**Comment by PaulMorris** [comment]
Thanks @jasonaowen , I'll use a single commit for smaller templates like this in the future.

**Pull request merged**
