### PR TITLE
Show current build status in the README

### PR DESCRIPTION
**Pull request by cecilia-donnelly**
Tiny PR. :)

### CODE REVIEW

**Comment by cecilia-donnelly** [comment]
Hmmmm I'm not sure why the build is failing, though!  alanis morissette ironic dot gif

**Comment by jasonaowen** [comment]
Oh fun, now our builds are dependent on third-party servers' uptime. :slightly_frowning_face: 

> Could not GET 'http://dl.bintray.com/djmijares/gradle-plugins/com/github/jacobono/gradle-jaxb-plugin/1.3.6/gradle-jaxb-plugin-1.3.6.pom'. Received status code 500 from server: Internal Server Error

**Comment by cecilia-donnelly** [comment]
Aha:

```
FAILURE: Build failed with an exception.

* What went wrong:

A problem occurred configuring root project 'psm-app'.

> Could not resolve all dependencies for configuration ':classpath'.

   > Could not resolve com.github.jacobono:gradle-jaxb-plugin:1.3.6.

     Required by:

         project :

      > Could not resolve com.github.jacobono:gradle-jaxb-plugin:1.3.6.

         > Could not get resource 'http://dl.bintray.com/djmijares/gradle-plugins/com/github/jacobono/gradle-jaxb-plugin/1.3.6/gradle-jaxb-plugin-1.3.6.pom'.

            > Could not GET 'http://dl.bintray.com/djmijares/gradle-plugins/com/github/jacobono/gradle-jaxb-plugin/1.3.6/gradle-jaxb-plugin-1.3.6.pom'. Received status code 500 from server: Internal Server Error

* Try:

Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED
```

**Comment by jasonaowen** [comment]
@cecilia-donnelly I reran the Travis jobs and they passed; just some transient network issue, apparently.

**Pull request merged**
